### PR TITLE
feat:-add wishlist page

### PR DESCRIPTION
**Pull request by shubhamkumar648**
1.add wishlisht page
wishlist

### CODE REVIEW

**Review by rahulcs754 — APPROVED** [review]
nice code and good design

**Review by sadathshariff — APPROVED** [review]
Good use of utility classes and everything looks clean

**Comment by shubhamkumar648** [comment]
> nice code and good design

thanks you

**Comment by shubhamkumar648** [comment]
> nice code and good design

thank you

**Pull request merged**
