### PR TITLE
feat:Prodct list page

### PR DESCRIPTION
**Pull request by shubhamkumar648**
Screenshot from 2022-02-15 12-16-31

add:- filter in product list
add: -add a vertical card in the main section

### CODE REVIEW

**Review by ttahm3d — APPROVED** [review]
Looks good. Can be merged

**Comment by shubhamkumar648** [comment]
> Looks good. Can be merged

Thank you Tahir for review

**Review by vivekmehto — APPROVED** [review]
Good use of card components. just one suggestion you can give some padding to ``aside`` apart from that everything seems good to me.

**Review by rahulcs754 — APPROVED** [review]
no  changes from my side

**Comment by shubhamkumar648** [comment]
> Good use of card components. just one suggestion you can give some padding to `aside` apart from that everything seems good to me.

thank you Vivek , I will do

**Pull request merged**
